### Provider Master Prep Workflow
* Creating a reusable master provider file to clean provider names

In [1]:
### Importing required libraries
import pandas as pd

In [2]:
### Reading the providers CSV file
providers_data = pd.read_csv('../data/bdc_us_provider_list_J25_03mar2026.csv')
providers_data.head()

     frn  provider_id                               holding_company
0  12609       240058                        Mid-Hudson Cablevision
1  12781       240068                            Neu Ventures, Inc.
2  13722       131087  Rainbow Telecommunications Association, Inc.
3  14936       240058                        Mid-Hudson Cablevision
4  17640       131060                      TPC ACC Acquisition, LLC

In [5]:
### Reading provider holding company XLSX sheet
providers_holding_company = pd.read_excel('../data/BDC Provider ID Table of Service Providers.xlsx')
providers_holding_company.head()

,Provider Name,Holding Company,Operation Type,FRN,Provider ID
0,"@Link Services, LLC","AtLink Services, LLC",Non-ILEC,16085920,290004
1,1 Point Communications,1 Point Communications,Non-ILEC,21352968,270002
2,101Netlink,101Netlink,Non-ILEC,18247254,190002
3,"123.Net, Inc","123.Net, Inc.",Non-ILEC,8590846,460000
4,"1Path Managed Services, LLC","1Path Managed Services, LLC",Non-ILEC,34347336,490000

In [6]:
### Renaming columns for merging
providers_data.rename(columns={'provider_id': 'Provider ID'}, inplace=True)

In [7]:
### Merging the two datasets on the 'Provider ID' column
merged_data = pd.merge(providers_data, providers_holding_company, on='Provider ID', how='left')
### Displaying the merged dataset
merged_data.head()

,frn,Provider ID,holding_company,Provider Name,Holding Company,Operation Type,FRN
0,12609,240058,Mid-Hudson Cablevision,CATSKILL MOUNTAIN CABLEVISION,Mid-Hudson Cablevision,Non-ILEC,12609.0
1,12609,240058,Mid-Hudson Cablevision,"MID-HUDSON CABLEVISION, Inc.",Mid-Hudson Cablevision,Non-ILEC,14936.0
2,12609,240058,Mid-Hudson Cablevision,Mid-Hudson Data Corp,Mid-Hudson Cablevision,Non-ILEC,15337090.0
3,12781,240068,"Neu Ventures, Inc.","NEU VENTURES, INC.","Neu Ventures, Inc.",Non-ILEC,12781.0
4,13722,131087,"Rainbow Telecommunications Association, Inc.",RAINBOW COMMUNICATIONS LLC,"Rainbow Telecommunications Association, Inc.",Non-ILEC,13722.0